### ISSUE TITLE
validateur en mousse

### ISSUE THREAD

**Issue by bcopin** [KleeGroup/focus4#108]
Le validateur sur les nombres est foireux, il ne s'arrête pas lorsqu'il rencontre une erreur de format (https://github.com/KleeGroup/focus4/blob/master/src/entity/validation.ts#L59), et il ne prend pas en compte les espaces alors qu'il devrait les refuser.

**Comment by JabX** [comment]
La correction pour la v8 ne concerne que la seconde partie (le reste ça marchait déjà correctement).

Je t'ai fait une 9.6.5 rien que pour toi, normalement tu peux la prendre sans problème.
