### ISSUE TITLE
[Form] Typer l'erreur de validation de formulaire

### ISSUE THREAD

**Issue by sebez** [KleeGroup/focus4#129]
## Comportement constaté

Sur mon projet, quand on click sur un bouton de sauvegarde : 
- Si une erreur de service arrive, le `fetch` ajoute un toast => OK
- Si une erreur de formulaire invalide arrive, l'utilisateur n'a pas de feedback

Code de `makeFormActions` : 

``` javascript
if (formNode.form && !formNode.form.isValid) {
    return Promise.reject({error: "Le formulaire est invalide", detail: formNode.form.errors});
}
```

L'erreur est loguée dans la console.

## Besoin

Sur mon projet, la cliente souhaite que l'utilisateur ait un feedback en cas de formulaire invalide.

Notamment, nous avons des formulaires avec onglet, et le champ invalide n'est pas forcément visible au click sur le bouton de sauvegarde.

## Implémentation sur le projet

Il suffit d'ajouter un catch à l'appel de mon action de save :
```javascript
action().catch((reasons: any) => {
                /** Cas d'une erreur de formulaire : on ajoute un toast. */
                if (reasons.error) {
                    messageStore.addErrorMessage(getFormInvalidMessage(reasons));
                }

                /** On relance. */
                throw reasons;
            });
```

J'ai alors besoin de distinguer le cas d'une erreur de formulaire invalide d'une erreur de service (ou autre).

Pour l'instant je me base uniquement sur la présence d'un champ `error`, c'est un peu grossier.

## Comportement attendu

Il serait élégant d'homogénéiser les format des erreurs entre les erreurs de services et les erreurs de formulaire invalide, et de les typer.

Par exemple avec un champ `$errorType : "invalidForm" | "serverError"`

On pourra alors écrire : 
```javascript
action().catch((reasons: any) => {
                /** Cas d'une erreur de formulaire : on ajoute un toast. */
                if (reasons.$errorType === "invalidForm") {
                    messageStore.addErrorMessage(getFormInvalidMessage(reasons));
                }

                /** On relance. */
                throw reasons;
            });
```

**Comment by JabX** [comment]
Le problème du `$errorType` c'est que tu ne vas pas forcément recevoir des erreurs sous un format correct depuis ton action de `save`, par exemple quand tu as des erreurs au niveau de la requête elle-même ou que ta requête ne renvoie pas du JSON... Je préfère renvoyer les erreurs sous le format le plus brut possible pour ne pas à fourrer mon nez à des endroits qui ne me regarde pas...

Ceci étant dit, le format de l'erreur de validation n'est pas satisfaisant, il faudrait en effet l'indiquer plus clairement qu'avec des propriétés comme `error` et `detail`. Un simple flag du type `$validationError: true` en plus me semble suffisant par exemple (avec le i18n associé pour le message bien sûr)

Ce que je remarque aussi avec ton exemple c'est qu'il manqu'un `onFormError` pour faire ce que tu fais dans ton `catch` à la main, puisque dans le cas général l'utilisateur n'appelle pas `save()` à la main, donc il ne peut pas y mettre le `catch`.

**Comment by sebez** [comment]
OK, cela répond à mon besoin.
