### ISSUE TITLE
[RECHERCHE AVANCEE] Filtres s'affichent lors de redimensionnement de la fenêtre

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus4#31]
Quand on redimensionne la fenêtre, la liste des filtres s'affiche alors que l'utilisateur n'a pas cliquer pour l'ouvrir

![image](https://user-images.githubusercontent.com/8983628/28074088-fe1c1196-6657-11e7-8a8e-f3b217761f5f.png)

**Comment by JabX** [comment]
C'est toujours le cas ? J'avais retesté sur mon appli et j'avais pas reproduit

**Comment by pierbrisson** [comment]
Yes, ça le fait toujours

**Comment by JabX** [comment]
Probablement corrigé par cc239977b6a44baa082677406a29a30e688a345f (et c'est même pas sur votre version), en vrai ça fait longtemps, s'il faut vraiment corriger tu pourra rouvrir une autre issue
