### ISSUE TITLE
Search & List

### ISSUE THREAD

**Issue by jordanbenzacken** [KleeGroup/focus4#42]
- unifier show more dans la liste (virer de results) 
- virer liststore avec service (on utilise que le searchstore) 
- consolider l'ensemble (ne pas avoir besoin de préciser store + data dans StoreList)

But : pouvoir utiliser StoreList à la place de AdvancedSearch gratos.

**Comment by JabX** [comment]
Les points 2 et 3 sont fait dans 159188e0272897116012342a6590ea4e87f98e1f (les modules list et search ne sont plus séparés d'ailleurs, c'était déjà chiant et ça allait devenir pire)

En bonus tu pourras aussi utiliser StoreTable aussi gratuit avec un store de recherche (quid de l'AdvancedSearch avec des tableaux à la place de listes ?)
