### ISSUE TITLE
[Recherche avancée] traduction des id sur autocompletion

### ISSUE THREAD

**Issue by TomGallon** [KleeGroup/focus4#64]
Dans la recherche avancée, je recherche avec une autocompletion.
![image](https://user-images.githubusercontent.com/5349745/41726999-9f698d96-7573-11e8-8673-83d4c980ad64.png)

Au niveau de ma recherche, une recherche sur l'ID est lancée

![image](https://user-images.githubusercontent.com/5349745/41726963-8d7f9508-7573-11e8-8a68-7cda4178b5cd.png)

La facette s'affiche avec l'id.

c'est pas très compréhensible pour l'utilisateur.
A-t-moyen de corriger cela dans Focus ?

merci :)

**Comment by JabX** [comment]
Ouais bah clairement c'est un peu la merde sur ce sujet-là, et je pense pas qu'on ait beaucoup de solutions possibles.

Pour la barre de recherche, le problème c'est qu'on est un peu obligé de mettre le code dedans puisque c'est texto ce qui est envoyé au serveur. Je ne vois pas comment on pourrait gérer la saisie s'il fallait vérifier à chaque frappe si elle correspond à une valeur possible… à ce moment-là, si tu voulais vraiment taper le nom de la ville dans la barre de recherche, il vaudrait mieux l'ajouter au champ de recherche au lieu de vouloir en faire un filtre. Sinon, si tu insistes pour que ça soit un critère, alors il ne faudrait pas l'afficher dans la barre de recherche, en ajoutant une propriété supplémentaire permettant de filtrer quels critères sont visibles/saisissables dans la barre (pour l'instant c'est tout ou rien).

Pour l'affichage du chip, c'est un peu tendu également parce que, à l'inverse des facettes qui viennent du serveur dans un objet `{code, label}`, les filtres sont gérés uniquement sur le client, comme des champs. L'affichage des valeurs de filtres dans un chip est l'équivalent d'un `fieldFor` simple, alors qu'ici on aurait besoin d'un `selectFor` ou `autocompleteFor`. On pourrait imaginer un moyen de spécifier dans l'AdvancedSearch critère par critère la liste de référence/le keyresolver a utiliser si nécessaire, ou bien on pourrait aussi faire plus simple en choisissant de ne pas afficher les chips de filtre (déjà possible), ou d'imaginer une propriété supplémentaire comme proposé pour la barre.

Quoiqu'il en soit ce n'est pas un bug mais une limitation connue de l'implémentation choisie 😛

**Comment by c3dr0x** [comment]
Pour les chips on est pas loins, on peut déjà donner un displayFormatter mais de keyresolver... https://github.com/KleeGroup/focus4/blob/v9/src/collections/components/search/summary.tsx#L61

Le problème réél vient de Kinetix pour le moment. Les filtres sont forcément des recherches par term et ne peuvent pour le moment être full text... Sinon on pourrait filtrer sur les libellés plutôt que sur des codes

**Comment by JabX** [comment]
On va proposer de pouvoir spécifier un keyResolver par filtre dans les chips des summary (qui pourra être asynchrone), ce qui devrait résoudre le gros du problème.
