### ISSUE TITLE
[AdvancedSearch] Issue with checkbox being lost

### ISSUE THREAD

**Issue by c3dr0x** [KleeGroup/focus4#67]
When using AdvancedSearch with infinite scroll.

You check some line, when scroll triggers a load for next page, the checked boxes are lost.

**Comment by JabX** [comment]
Toute action qui relance la recherche vide la sélection (parce qu'on remplace les éléments retournés par des nouveaux), mais dans le cas du scroll vu qu'on ne touche pas aux éléments existants en effet ce n'est pas nécessaire.
