### ISSUE TITLE
Reproduire le comportement "Scrollspy" sur d'autres composants (en particulier : la recherche/les listes)

### ISSUE THREAD

**Issue by TomGallon** [KleeGroup/focus4#68]
sur beaucoup de nos pages de type liste (ou longues), on aimerait que le header soit sticky
Peux-tu ajouter un composant décorateur qui rende le composant fils sticky quand il sort (presque) de la page...
et il faudrait que ce composant englobe la bar d'action sur la recherche avancée... car quand les listes sont longues et qu'on fait de la sélection en masse, il faut remonter en haut de l'écran pour avoir accès au bouton et pour lancer l'action.

**Le besoin est assez urgent pour notre projet.**

Merci :)

**Comment by JabX** [comment]
Le comportement souhaité est à mon avis plus proche de celui du header que de celui du scrollspy, mais la solution devra probablement combiner les deux : la complexité du header vient du fait qu'il faut gérer proprement le contenu en dessous, et celle du scrollspy vient du fait qu'il faut calculer sa position précise, qui dépend justement de celle du header.

On a besoin d'un composant un minimum non spécialisé puisqu'il faudrait pouvoir rendre sticky au moins la barre d'actions seule ou la barre d'actions + le résumé de recherche, et voire aussi le conteneur de facette (pour ce dernier, ce serait exactement la même chose que le scrollspy).

Le challenge dans tout ça serait aussi de réussir à réutiliser le plus possible de code entre les différentes implémentations/composants...

**Comment by c3dr0x** [comment]
Exemple de scrollspy externalisé:

````tsx
// Libs
import { action, computed, observable, observer, React } from "focus4";
import * as PropTypes from "prop-types";
import { findDOMNode } from "react-dom";

// Styles
import "./__style__/scrollspy.scss";

@observer
export class Scrollpsy extends React.Component {
    @observable private offsetTop = 0;
    @observable private scrollTop = 0;

    static contextTypes = {
        layout: PropTypes.object,
        header: PropTypes.object
    };

    context!: {
        layout: {
            contentPaddingTop: number;
        };
        header: {
            marginBottom: number;
            topRowHeight: number;
        };
    };

    componentDidMount() {
        window.addEventListener("scroll", this.onScrollOrResize);
        window.addEventListener("resize", this.onScrollOrResize);
        this.onScrollOrResize();
    }

    componentDidUpdate() {
        this.onScrollOrResize();
    }

    componentWillUnmount() {
        window.removeEventListener("scroll", this.onScrollOrResize);
        window.removeEventListener("resize", this.onScrollOrResize);
    }

    /** Synchronise le scroll/resize de la page avec les observables qui les représentent. */
    @action.bound
    private onScrollOrResize() {
        this.scrollTop = document.documentElement.scrollTop || document.body.scrollTop;
        this.offsetTop = (findDOMNode(this) as Element).getBoundingClientRect().top;
    }

    /** Détermine la position du menu (absolue avant menuOffset, fixe après) */
    @computed.struct
    private get position() {
        const offset =
            this.context.header.topRowHeight + this.context.header.marginBottom + this.context.layout.contentPaddingTop;

        const isFixed = this.scrollTop !== 0 && this.offsetTop < offset;

        return {
            position: isFixed ? ("fixed" as "fixed") : ("absolute" as "absolute"),
            top: isFixed ? offset : 0
        };
    }

    render() {
        return (
            <div className="c-scrollspy">
                <div style={this.position}>{this.props.children}</div>
            </div>
        );
    }
}

export function withScrollSpy(Component: React.ComponentClass<any>) {
    return (props: any) => (
        <Scrollpsy>
            <Component {...props} />
        </Scrollpsy>
    );
}

```

Le CSS associé:
  
```css
.c-scrollspy {
    position: relative;
}
```

Et son utilisation:

```tsx
export const InternvenantMenuScroll = withScrollSpy(InternvenantMenu);
```

**Comment by JabX** [comment]
Je sais pas si on va pouvoir vraiment faire un composant qui marche tout le temps, mais au moins il faudrait pouvoir rendre sticky le bloc "Summary + ActionBar" et la liste des facettes dans une recherche avancée, et une ActionBar seule en dehors de la recherche.
