### ISSUE TITLE
[Layout] Enhance Dx for Header

### ISSUE THREAD

**Issue by c3dr0x** [KleeGroup/focus4#73]
Today it's kind of clumsy to handle the page headers:

- 1st, you need to handle it separately from pages. 
- 2nd, attempts to factor code to handle header always became messy.

I propose a new approach using new React 16 portals.

The goal is: 

1. to keep the header the closest possible to the page it is displayed for
2. have a lean api easy to instantiate it

My proposition:

```jsx
            <Header
                title="staffing.publicationDetail.title"
                hasBackButton
                primary={[{ icon: "settings", onClick: openPublicationSettingsPopup }]}
            >
                <PublicationHeaderRow publication={this.store} />
                <PublicationHeaderRow publication={this.store} isDeployed />
            <Header>
```

You can give it:

- A title
- If it displays a back button
- primary/secondary actions
- 1 or 2 childs
    - 1st child will be the summary
    - 2nd child will be the content

If you give it only one child then the header won't be able to expand

Using portals you can use it as the 1st component of a page. Meaning that you always have the header of the current displayed page, no need to handle them aside. If you need to have a specific behavior for a page you simply not use this new header on that page.

The implementation is:

```jsx
// Libs
import { i18n, observable, observer, React } from "focus4";
import ReactDOM from "react-dom";

// Components
import {
    HeaderActions,
    HeaderBarLeft,
    HeaderBarRight,
    HeaderContent,
    HeaderScrolling,
    HeaderSummary,
    HeaderTopRow,
    PrimaryAction,
    SecondaryAction
} from "focus4/layout";
import Button from "react-toolbox/lib/button";
import { OpaleBarRight } from "./bar-right";

export interface OpaleHeaderProps {
    /** Title for header. */
    title: string;
    /** Hsa back button @default false */
    hasBackButton?: boolean;
    /** Actions principales. */
    primary?: PrimaryAction[];
    /** Actions secondaires. */
    secondary?: SecondaryAction[];
}

/**
 * RS Header component.
 */
@observer
export class OpaleHeader extends React.Component<OpaleHeaderProps> {
    @observable isMounted = false;

    componentDidMount() {
        this.isMounted = true;
    }

    render() {
        const { title, hasBackButton = false, primary, secondary, children } = this.props;

        const container = document.getElementById("app-header");
        const childrenCount = React.Children.count(children);
        const childrenArray = React.Children.toArray(children);

        let summary: React.ReactChild | undefined;
        let content: React.ReactChild | undefined;
        let canDeploy = false;

        if (children && childrenCount >= 1) {
            summary = childrenArray[0];
        }
        if (children && childrenCount >= 2) {
            content = childrenArray[1];
            canDeploy = true;
        }

        if (this.isMounted && container) {
            return ReactDOM.createPortal(
                <HeaderScrolling canDeploy={canDeploy}>
                    <HeaderTopRow>
                        <HeaderBarLeft theme={{ item: "header__bar-left" }}>
                            {hasBackButton && (
                                <Button
                                    theme={{ button: "c-back-button o-icon--large" }}
                                    icon="arrow_back"
                                    onClick={() => window.history.back()}
                                />
                            )}
                            {i18n.t(title)}
                        </HeaderBarLeft>
                        <HeaderSummary>{summary}</HeaderSummary>
                        <HeaderBarRight theme={{ item: "header__bar-right" }}>
                            <OpaleBarRight />
                        </HeaderBarRight>
                    </HeaderTopRow>
                    <HeaderContent>{content}</HeaderContent>
                    <HeaderActions primary={primary} secondary={secondary} theme={{ actions: "c-header__fab" }} />
                </HeaderScrolling>,
                container
            );
        }

        return null;
    }
}
```

It misses at least for now:

- Styles
- Be split in two. The right part of an application is always the same across the app (user name, some always available modules, etc) so each project would wrap it within an intermediary component setting the right part for its project.
- Maybe be able to give the container name, or exposing a component from focus that will only add the container in the layout (I prefer the later one)
- Maybe having the back button as a prop in the same intermediary component, I'm not sure all projects want to use the `history.back()`

**Comment by JabX** [comment]
L'implémentation que tu proposes est trop restrictive mais dans l'idée c'est sûr que c'est plus sympa et pratique de gérer le header au niveau de la page concernée...

L'idée derrière la refonte précédente du header était de le rendre ouvert et facilement extensible/modifiable, et je pense que c'est un point à conserver pour le futur. Après je suis sûr que ça pourrait être mieux fait, donc si on y touche pour utiliser des Portals nativement on devrait réfléchir à l'API un peu plus dans le détail.

En attendant (pas sûr qu'on arrive à se dégager du temps dans les semaines qui viennent), y a rien qui bloque dans Focus pour le faire (et tu la déjà fait), donc je serai d'avis que dans un premier temps on laisse la gestion aux projets (qui peuvent recopier ce que tu as fait).

**Comment by c3dr0x** [comment]
Oui, découper en deux les parties portal et header "classique" est bien. 
Mais garder un wrapper pour le header tel qu'il est présenté là est important à mon avis, il couvre 80-90% des besoins. Et c'est assez infect pour ceux-là de devoir tout le temps remettre les 10 composants pour faire l'équivalent. 
Je vois cette partie de la proposition comme le advancedSearchFor, il propose un cadre fixé mais on peut instancier tous les composants un à un lorsque l'on souhaite faire autre chose.

**Comment by JabX** [comment]
Peut-être aussi qu'on a pas vraiment besoin de découper le header en autant de composants différents, probablement qu'on pourrait se défaire de la séparation Summary/Content qui se répète quasiment tout le temps, supprimer le HeaderTopRow qui peut se déduire tout seul, retirer le BarLeft qui ne sert qu'à faire un back et faire comme toi avec juste une prop "showBackButton"...

On pourrait alors se retrouver avec une API plus simple, genre : 
```tsx
<Header canDeploy actions showBackButton>
    <HeaderContent /> // récupère la prop "mode" automatiquement depuis le parent
    <HeaderBarRight />
</Header>
```
Après j'ai pas vraiment joué avec les Portals et je ne sais pas trop ce qu'on peut faire avec mais j'imaginerai bien que chaque composant puisse redéfinir le header et qu'il ne puisse spécifier que ce qu'il change.

Par exemple : 
```tsx
// header de base
<Header canDeploy={false} showBackButton={true}>
    <HeaderContent>Mon appli Focus</HeaderContent>
    <HeaderBarRight>Username <a>Déconnexion</HeaderBarRight>
</Header>

// Et ensuite dans ma page je peux le surcharger partiellement
<Header canDeploy actions={{primary: [{icon: "add"}]>
     <HeaderContent Component={MyHeader} /> // MyHeader devrait avoir dans ce cas une prop "mode" et serait instancié avec.
</Header>
// Tout ce qui a été spécifié et non surchargé est gardé.
```

Je doute qu'une API comme celle-ci soit réellement possible mais ça me semblerait idéal.

**Comment by c3dr0x** [comment]
Nop, on peut pas surcharger que des morceaux de portals, où alors il faut multiplier les portals mais ça me parait être une mauvaise solution
L'idée est que si le composant parent est démonté alors le contenu du portal cible est aussi démonté, logique en fait

Je ne suis pas forcément pour fusionner autant les composants, j'ai eu des cas spécifiques où j'étais content des les avoirs autant découpés ^^

Par contre je ne vois pas l'intérêt dans ta modif de devoir préciser le `canDeploy` puis d'avoir avec un composant avec un mode, par rapport à ma proposition où tu donnes un ou deux composants d'où il détermine le `canDeploy` et la répartition. c'est plus souple car les deux composant peuvent ne rien avoir en commun

Sinon pour l'histoire des composants par défaut. Ce que je peux proposer c'est de faire une factory à Header qui prends en paramètre par exemple la `<BarRight />` et un Titre générique et qui les appliques si rien d'autre n'es précisé. Du coup on a ton principe de surcharge partielle. Et on se rapproche d'un `advancedSearhcFor` dont je parlais avec peut-être un` createDefaultHeader(title, <BarRight />, <backButton />)` qui sert à créer le composant `<DefaultHeader  />` qu'on utilise ensuite comme proposé

**Comment by JabX** [comment]
Ca fait quoi du coup si tu essaies de redéfinir plusieurs fois dans ta page un Portal sur le même élément, ça plante ? Ou ça remplace le premier ? Si on ne peut pas le redéfinir je trouve que ça perd un peu d'intérêt mais ça serait tout de même déjà ça de pris.

En pratique je n'ai jamais vu d'exemple d'un composant de summary qui n'avait rien à voir avec le cartridge associé, et d'ailleurs toi même dans ton exemple tu utilises le même composant avec simplement une prop renseignée en plus…

Concernant ta proposition avec une factory de header avec un header par défaut, si tu remplaces un header par un autre c'est comme si tu détruisais intégralement l'ancien pour le remplacer par le nouveau ou bien React peut-il faire de la mise à jour "intelligente" comme avec des composants normaux ? Si oui, alors ça serait une solution plutôt idéale, mais sinon j'ai l'impression que ça pourrait causer pas mal d'effets de bord indésirable (comme le pb avec le scrollspy que tu as eu par exemple).

En y réfléchissant un peu plus ça ne serait peut être pas une si mauvaise idée que ça d'avoir plusieurs portals en fait..
