### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by everdurand** [KleeGroup/focus4#78]
Pour permettre l'utilisation du japonais serait-il possible :
- d'utiliser moment.localeData() plutôt que moment.locale()
- nécessite probablement de faire une conversion au format adéquat des valeurs (months, weekday, etc...)

Merci :)

**Comment by JabX** [comment]
![image](https://user-images.githubusercontent.com/3266897/45849713-6dec8900-bd33-11e8-8abb-319634af7725.png)

C'est bien ça ? (l'affichage de la date dans le panneau violet du haut est déjà modifiable)

**Comment by JabX** [comment]
release 8.7.10
