### ISSUE TITLE
[Bug] Les composants de lignes sont recréés quand on sélectionne des lignes

### ISSUE THREAD

**Issue by Aldarick** [KleeGroup/focus4#83]
Du coup, l'état du composant est perdu, ce qui peut poser problème si on veut en avoir (ex : état de hover, ou pire, si on a un champ texte de saisie)

**Comment by JabX** [comment]
Bah en fait, non.
![foot](https://user-images.githubusercontent.com/3266897/46917769-e52bda80-cfca-11e8-9a34-7edaebdf40d3.gif)
Ton problème doit venir d'ailleurs (je sais qu'on avait diagnostiqué ensemble)...

**Comment by Aldarick** [comment]
En effet, le problème venait d'ailleurs (composant de ligne recréé à chaque render de la liste)
