### ISSUE TITLE
[Form] L'action du save devrait faire un Promise.reject en cas d'erreur de validation

### ISSUE THREAD

**Issue by sebez** [KleeGroup/focus4#89]
Quand on appelle l'action du `save` du formulaire, et que le service est en erreur, la promesse n'est pas rejetée.

Si on chaîne un `then` sur l'appel du `save`, il est donc appelé à tord.

**Comment by JabX** [comment]
C'est pas le service qui est en erreur dans ton cas, c'est la validation. Si le service est en erreur ça rejette bien la promesse.

**Comment by JabX** [comment]
![image](https://user-images.githubusercontent.com/3266897/46978542-8734eb00-d0cf-11e8-965c-c4913d53905d.png)
Et la promesse rejette les erreurs, si c'est pas beau !

**Comment by JabX** [comment]
Et pour faire les choses bien :
![image](https://user-images.githubusercontent.com/3266897/46978721-f4488080-d0cf-11e8-9161-80e5762bdca1.png)
![image](https://user-images.githubusercontent.com/3266897/46978769-1b9f4d80-d0d0-11e8-9d9b-789991f0818c.png)
Les objets d'erreurs sont accessibles et typés !
