### ISSUE TITLE
Composant d'affichage de champ booléen

### ISSUE THREAD

**Issue by sebez** [KleeGroup/focus4#97]
## Besoin
Rendre un champ de type booléen avec libellé personnalisable pour les valeurs.

## Implémentation
On pourrait avoir un utilitaire `booleanFor` qui prend en entrée en entityField de type booléen, avec des props `labelYes` et `labelNo`.

<code javascript>{booleanFor(isZorro, {labelYes : 'Zorro', labelNo: 'Bernardo'})}</code>

Actuellement, il n'existe qu'un composant `BooleanRadio` dont les libellés ne sont pas surchargeables.

**Comment by JabX** [comment]
Le problème avec ce que tu proposes c'est que tu mélanges le type de composant que tu veux (un radio) et le type du champ que tu veux afficher (un booléen). Certes, il existe des utilitaires séparés pour l'autocomplete et le select, mais c'est parce qu'il ont une API différente du simple fieldFor et ça n'a rien a voir avec le type du champ.

Réaliser un simple composant d'affichage radio d'un booléen, utilisé comme InputComponent, avec des libellés personnalisables via inputProps serait largement suffisant pour résoudre ton problème. J'ai d'ailleurs exactement ce composant sur un de mes projets d'ailleurs. Je pourrais l'intégrer dans Focus, éventuellement.
